### ISSUE TITLE
Mismatching between mmt-security and Probe: less alerts

### ISSUE THREAD

**Issue by Frankccv** [Montimage/mmt-probe#5]
I tried to test mmt-sec-standalone and probe with the same pcap. This pcap shows a flooding attack of get requests.
The commands that I tried were 
./probe -t flooding_get.pcapng
And
./mmt-sec-stadalone -t flooding_get..pcapng

And as a result I obtain two differents output. MMT-Security rises 19 alerts while Probe rises only 1 alert, as in the images attached.
![mmt-probe](https://github.com/Montimage/mmt-probe/assets/56630595/3a7b711e-bff5-4895-90fe-86c3629a83a2)

![mmt-security-standalone](https://github.com/Montimage/mmt-probe/assets/56630595/c55adeff-0d1e-4367-a37d-731dfcb79385)

**Comment by nhnghia** [comment]
I think that the cause can be [this parameter](https://github.com/Montimage/mmt-probe/blob/v1.5.10/mmt-probe.conf#L182): By default, MMT-Probe will ignore the security verification on the left of an IP flow when an alert is detected. This is to say that it raises at most one alert per IP flow.

Can you try again within new value, e.g.,:  `ignore-remain-flow = false`

**Comment by Frankccv** [comment]
Perfect, thank you
