### ISSUE TITLE
The default configuration doesn't work

### ISSUE THREAD

**Issue by Frankccv** [Montimage/mmt-probe#6]
When I try to execute probe I get the following error:

./mmt-probe.conf:718: no such option 'output-format'

mmt-probe: Error: configuration file './mmt-probe.conf' could not be parsed.

/opt/mmt/probe/mmt-probe.conf:718: no such option 'output-format'

mmt-probe: Error: configuration file '/opt/mmt/probe/mmt-probe.conf' could not be parsed.

Aborted

**Comment by nhnghia** [comment]
I think that you didn't use the latest version of mmt-probe. If so, you can delete line 781
